stages:
  data_ingestion:
    cmd: python3 05_ml_pipeline_dvc_s3/src/data_ingestion.py
    deps:
    - 05_ml_pipeline_dvc_s3/src/data_ingestion.py
    outs:
    - 05_ml_pipeline_dvc_s3/data/raw

  data_preprocessing:
    cmd: python3 05_ml_pipeline_dvc_s3/src/data_preprocessing.py
    deps:
    - 05_ml_pipeline_dvc_s3/data/raw
    - 05_ml_pipeline_dvc_s3/src/data_preprocessing.py
    outs:
    - 05_ml_pipeline_dvc_s3/data/interim

  feature_engineering:
    cmd: python3 05_ml_pipeline_dvc_s3/src/feature_engineering.py
    deps:
    - 05_ml_pipeline_dvc_s3/data/interim
    - 05_ml_pipeline_dvc_s3/src/feature_engineering.py
    outs:
    - 05_ml_pipeline_dvc_s3/data/processed

  model_building:
    cmd: python3 05_ml_pipeline_dvc_s3/src/model_building.py
    deps:
    - 05_ml_pipeline_dvc_s3/data/processed
    - 05_ml_pipeline_dvc_s3/src/model_building.py
    outs:
    - 05_ml_pipeline_dvc_s3/models/model.pkl

  model_evaluation:
    cmd: python3 05_ml_pipeline_dvc_s3/src/model_evaluation.py
    deps:
    - 05_ml_pipeline_dvc_s3/models/model.pkl
    - 05_ml_pipeline_dvc_s3/src/model_evaluation.py
    metrics:
    - 05_ml_pipeline_dvc_s3/reports/metrics.json
